baseURL = "https://brucechanglongxu.github.io/"
languageCode = "en-us"
title = "Bruce C. Xu"
theme = "dario"

[params]
  description = "Notes, research, and projects."
  colorScheme = "toggle" # or "system" | "light" | "dark"

  [params.author]
    name = "Bruce Changlong Xu"
    email = "you@example.com"
  math = true

# Show these sections in nav / homepage
mainSections = ["initiatives", "essays", "lectures"]

[build]
  buildFuture = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = true